# ---------- Stage 1 ----------
FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

# ---------- Stage 2 ----------
FROM node:22-slim

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

CMD ["npm", "start"]